spring:
  application:
    name: Spring-boot-cloud-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: Spring-boot-cloud-feign
    api-b:
      path: /api/b/**
      serviceId: Spring-boot-cloud-ribbon